---
- name: "Copy Secret : {{ secret_name }} : {{ secret_name }} : Lookup secret"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}"
    namespace: "{{ cert_manager_namespace }}"
  register: secret_info

- name: "Copy Secret : {{ secret_name }} : Assert that the secret exists"
  assert:
    that:
      - secret_info is defined
      - secret_info.resources is defined
      - secret_info.resources | length == 1
    fail_msg: "Unable to copy secret, the source Issuer's Secret ({{ secret_name }}) does not exist: {{ secret_info }}"

- name: "Copy Secret : {{ secret_name }}: Write new secret"
  vars:
    data: "{{ secret_info.resources[0] }}"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ common_services_namespace }}"
    definition: "{{ lookup('template', 'blanksecret.yml.j2') | from_yaml }}"
