---
# Delete Cert Manager deployments from cert-manager namespace so it does not clash with new ibm-cert-manager to be installed next
- name: "Delete JetStack cert-manager deployment"
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    name: cert-manager
    namespace: "{{ cert_manager_namespace }}"

- name: "Delete JetStack cert-manager-cainjector deployment"
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    name: cert-manager-cainjector
    namespace: "{{ cert_manager_namespace }}"

- name: "Delete JetStack cert-manager-webhook deployment"
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    name: cert-manager-webhook
    namespace: "{{ cert_manager_namespace }}"

# Check if cert-manager-webhook-ibm-cis deployment is present, if it is, then remove it (this is installed via mas_devops.suite_dns role)
- name: "Lookup cert-manager-webhook-ibm-cis deployment"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: cert-manager-webhook-ibm-cis
    namespace: "{{ cert_manager_namespace }}"
  register: cis_webhook_deployment

- name: "Delete JetStack cert-manager-webhook-ibm-cis deployment"
  when: cis_webhook_deployment.resources is defined and cis_webhook_deployment.resources | length > 0
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    name: cert-manager-webhook-ibm-cis
    namespace: "{{ cert_manager_namespace }}"
