---

# 1. Setup the EFS we will use in the cluster
# -----------------------------------------------------------------------------
- include_tasks: "tasks/efs-setup.yml"


# 2. Install AWS EFS CSI Operator
# -----------------------------------------------------------------------------
- name: "Install CSI Drivers Operator Group"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/operator-group.yml.j2"

- name: "Install AWS EFS CSI Operator Subscription"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/efs-csi-subscription.yml.j2"


# 3. Add AWS credentials to OpenShift secrets
# -----------------------------------------------------------------------------
- name: "Create Secret"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/aws-secret.yml.j2"


# 4. Install AWS EFS CSI DRIVER
# -----------------------------------------------------------------------------
- name: "Install AWS EFS CSI Driver"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/efs-csi-driver.yml.j2"


# 5. Create a Storage Class for aws efs
# -----------------------------------------------------------------------------
- name: "Create a Storage Class for aws efs"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/efs-csi-storage-class.yml.j2"
