---

mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"
mas_upgrade_supported_channels: ['8.6.x']

# cpd upgrade vars
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=35-upgrading-cloud-pak-data
# cpd35_meta_namespace: cpd-meta-ops
cpd_meta_namespace: ibm-common-services
cpd_services_namespace: cpd-meta-ops # reuse existing namespace that contains cpd v3.5 services
cpd_registry: cp.icr.io
cpd_registry_user: cp

# This is only used for cpd35, we have to use cp4d_hack_worker_nodes to set up the global image pull secret needed by cpd40
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"

cpd_primary_storage_class: 'ibmc-file-gold-gid'
cpd_metadata_storage_class: 'ibmc-block-gold'
cpd_upgrade_supported_services:
  - db2wh
  - wsl
  - wml
  - spark
  - aiopenscale
  - dmc
  - dods
  # - wd - by the time this role was implemented, there was no upgrade path available for watson discovery

# list of services that will be upgraded as first priority
cpd_services_list_priority1:
  - db2wh
  - wsl

# list of services that will be upgraded as second priority
cpd_services_list_priority2:
  - wml
  - dods
  - dmc
  - spark

# list of services that will be upgraded as third priority
cpd_services_list_priority3:
  - aiopenscale
