galaxy_info:
  author: André Marcelino
  description: Upgrade Service Binding Operator from preview channel (0.8v) to stable channel (1.0v)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - upgrade

dependencies:
  - role: ibm.mas_devops.ansible_version_check
