---
# Application specific variables for Health
mas_app_ws_fqn: healthworkspaces.apps.mas.ibm.com
mas_app_ws_apiversion: apps.mas.ibm.com/v1
mas_app_ws_kind: HealthWorkspace
mas_app_cfg_retries: 50
mas_app_cfg_delay: 480
