---
mas_app_ws_fqn: hputilitiesworkspaces.apps.mas.ibm.com
mas_app_ws_apiversion: apps.mas.ibm.com/v1
mas_app_ws_kind: HPUtilitiesWorkspace

mas_app_cfg_delay: 120
mas_app_cfg_retries: 30

cpd_ws_project_id: "{{ lookup('env', 'CPD_WS_PROJECT_ID') | default('', true) }}"
cpd_ws_project_name: "{{ lookup('env', 'CPD_WS_PROJECT_NAME') | default('wsl-mas-' + mas_instance_id + '-hputilities', true) }}" # default must be the same expected by cp4d_services role
