---
# Choose DNS Provider
# -----------------------------------------------------------------------------
dns_provider: "{{ lookup('env', 'DNS_PROVIDER') }}"

# Certificate Manager
# -----------------------------------------------------------------------------
cert_manager_namespace: ibm-common-services
cert_manager_service_account: ibm-cert-manager-controller

# MAS Domain
# -----------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_domain: "{{ lookup('env', 'MAS_DOMAIN') }}"

# Override the OCP ingress used in DNS entries
# -----------------------------------------------------------------------------
ocp_ingress: "{{ lookup('env', 'OCP_INGRESS') }}"

# Cloudflare DNS Integration
# -----------------------------------------------------------------------------
cloudflare_prod_issuer_name: "{{ mas_instance_id }}-cloudflare-le-prod"
cloudflare_stg_issuer_name: "{{ mas_instance_id }}-cloudflare-le-stg"

cloudflare_email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') }}"
cloudflare_apitoken: "{{ lookup('env', 'CLOUDFLARE_APITOKEN') }}"
cloudflare_zone: "{{ lookup('env', 'CLOUDFLARE_ZONE') }}"
cloudflare_subdomain: "{{ lookup('env', 'CLOUDFLARE_SUBDOMAIN') }}"

# IBM Cloud Internet Services DNS Integration
# -----------------------------------------------------------------------------
cis_prod_issuer_name: "{{ mas_instance_id }}-cis-le-prod"
cis_stg_issuer_name: "{{ mas_instance_id }}-cis-le-stg"

cis_email: "{{ lookup('env', 'CIS_EMAIL') }}"
cis_apikey: "{{ lookup('env', 'CIS_APIKEY') }}"
cis_crn: "{{ lookup('env', 'CIS_CRN') }}"
cis_subdomain: "{{ lookup('env', 'CIS_SUBDOMAIN') }}"

cis_apiservice:
  group_name: acme.cis.ibm.com

cis_webhook:
  image:
    repository: quay.io/ibmmas/cert-manager-webhook-ibm-cis
    tag: 1.0.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 443
  log_level: 1

# CP4D Integration
# -----------------------------------------------------------------------------
cpd_instance_namespace: "{{ lookup('env', 'CPD_INSTANCE_NAMESPACE') }}"
