galaxy_info:
  author: Caroline Azadze (@caroazad)
  description: Run IBM AI Applications' Must Gather tool against a MAS instance
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - mustgather

dependencies:
  - role: ibm.mas_devops.ansible_version_check
