---
# Note about Analytics Project Id (mas_app_settings_project_id):
# - It may come from environment variable CPD_WSL_PROJECT_ID OR
# - It may come from MAS Config Directory (written by cp4d_service role)
# - If not available, fail

# Default application spec for HPUtilities
mas_app_ws_spec:
  bindings:
    watsonstudio: system
  components: '{{ mas_appws_components | default({}, true) }}'
  settings:
    watsonstudio:
      projectid: "{{ mas_app_settings_project_id }}"
