---

# 1. Check that all properties are provided
# -----------------------------------------------------------------------------
- name: "Fail if local_output_dir is not provided"
  assert:
    that: local_output_dir is defined and local_output_dir != ""
    fail_msg: "local_output_dir property is required"

- name: "Fail if mustgather_namespace is not provided"
  assert:
    that: mustgather_namespace is defined and mustgather_namespace != ""
    fail_msg: "mustgather_namespace property is required"


# 2. Provide debug information to the user
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "Local Output Directory ............. {{ local_output_dir }}"
      - "Mustgather Namespace ............... {{ mustgather_namespace }}"


# 3. Start pod to allow access to pipeline PVs
# ------------------------------------------------------------------------------
- name: Start Pod to retrieve logs (if it doesn't already exist)
  kubernetes.core.k8s:
    apply: yes
    wait: yes
    wait_timeout: 120
    definition: "{{ lookup('template', 'templates/deployment.yml') }}"


# 4. Download the mustgather to local folder
# ------------------------------------------------------------------------------
- name: Search for Pod labelled app=mas-devops-mustgather-download
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app = mas-devops-mustgather-download
  register: _mustgatherDownloadPod

- name: "Copy /mustgathers from a mustgathers PV to local destination {{ local_output_dir }}"
  kubernetes.core.k8s_cp:
    namespace: "{{ mustgather_namespace }}"
    pod: "{{ _mustgatherDownloadPod.resources[0].metadata.name }}"
    remote_path: /mustgathers/
    local_path: "{{ local_output_dir }}"
    state: from_pod
