---
# 10. (optionally) Upgrade SBO to v1.0 - only if you upgraded to OCP v4.8
# -----------------------------------------------------------------------------
# MAS 8.7 fully supports both the preview and stable channels of the Red Hat
# service binding operator, however at some point before you eventually upgrade
# to MAS 8.8 you will need to upgrade to the stable channel.  The stable
# channel is not available in OCP 4.6
- name: "Upgrade SBO to v1.0 (stable)"
  include_tasks: tasks/sbo_upgrade/upgrade.yml
