galaxy_info:
  author: André Marcelino (@andrercm)
  description: Upgrade an existing CloudPak for Data v3.5 installation to v4.0
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - upgrade

dependencies:
  - role: ibm.mas_devops.ansible_version_check
