---

# We will update the cluster's default image pull secret with these credentials ... so this will impact
# everything from the entitled registry in all namespaces, not just CP4D
cpd_registry: cp.icr.io
cpd_registry_user: cp
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"

# We will use the IBM Cloud CLI to restart all worker nodes
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE') }}"
cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
