---
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"

common_services_namespace: ibm-common-services

# default_custom_cluster_issuer: "cis-letsencrypt-production-{{ mas_instance_id }}"
# custom_cluster_issuer: "{{ lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') | default(default_custom_cluster_issuer, true), lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') | default(None, true) }}"
custom_cluster_issuer: "{{ lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') }}"

cert_names:
  # CA for signing all the individual certs for internal use
  internal_ca: "{{ mas_instance_id }}-cert-internal-ca"
  # public certs
  public: "{{ mas_instance_id }}-cert-public"
  public_ca: "{{ mas_instance_id }}-cert-public-ca"

internal_certificate_issuer:
  name: "{{ mas_namespace }}-internal-issuer"

internal_ca_issuer:
  name: "{{ mas_namespace }}-internal-ca-issuer"
