---
# For versions >= 1.9.0 set to any desired namespace or use nvidia's recommended namespace (nvidia-gpu-operator)
gpu_namespace: "{{ lookup('env', 'GPU_NAMESPACE') | default('openshift-operators', true) }}"

# Set channel for install and updates
gpu_channel: "{{ lookup('env', 'GPU_CHANNEL') | default('v1.8', true) }}"

# Set driver version if needed
gpu_driver_version: "{{ lookup('env', 'GPU_DRIVER_VERSION') | default('450.80.02', true) }}"


# Variables for Node Feature Discovery Operator

# namespace to deploy nfd to
nfd_namespace: "{{ lookup('env', 'NFD_NAMESPACE') | default('gpu-operator-resources', true) }}"

# channel for nfd install and updates
nfd_channel: "{{ lookup('env', 'NFD_CHANNEL') | default('stable', true) }}"
