---

# 1. Install UDS
# -----------------------------------------------------------------------------
# If the user has provided uds_endpoint_url then it means they don't want to install
# UDS locally, but instead just generate a BASCfg for the instance defined by
# the input variables
- include_tasks: tasks/install/main.yml
  when:
    - uds_endpoint_url is not defined or uds_endpoint_url == ""


# 2. Generate the UDS configuration for MAS
# -----------------------------------------------------------------------------
- include_tasks: tasks/gencfg/main.yml
  when:
    - mas_instance_id is defined and mas_instance_id != ""
    - mas_config_dir is defined and mas_config_dir != ""
