apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: "{{ cpd_services_namespace }}"
spec:
  license:
    accept: true
    license: Standard
  # both storage classes for cpd uses ibmc-file-gold-gid when cpd 3.5 is installed using `cp4d_install` role
  # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=requirements-storage
  storageClass: "{{ cpd_primary_storage_class }}"
  zenCoreMetadbStorageClass: "{{ cpd_primary_storage_class }}"
