---
apiVersion: operator.ibm.com/v1
kind: NamespaceScope
metadata:
  name: cpd-upgrade-namespace-scope
  namespace: "{{ cpd_meta_namespace }}"
spec:
  csvInjector:
    enable: true
  namespaceMembers:
  - "{{ cpd_meta_namespace }}"                 # (Default) Replace with the Cloud Pak for Data platform operator project name
  - "{{ cpd_services_namespace }}"                  # Replace with the project where Cloud Pak for Data is installed
