---
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
mas_workspace_name: "{{ lookup('env', 'MAS_WORKSPACE_NAME') }}"

mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
