galaxy_info:
  author: André Marcelino (@andrercm)
  description: DB2 restore process
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - db2

dependencies:
  - role: ibm.mas_devops.ansible_version_check
