---
cos_type: "{{ lookup('env', 'COS_TYPE') }}" # "ibm" or "ocs"

# When these variables are defined we will create the ObjectStorageCfg resource,
# if either is missing then the configuration will not be generated
# ---------------------------------------------------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# OpenShift Container Storage Object Storage (ocs)
# ---------------------------------------------------------------------------------------------------------------------


# IBM Cloud Object Storage (ibm)
# ---------------------------------------------------------------------------------------------------------------------
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
ibmcloud_resourcegroup: "{{ lookup('env', 'IBMCLOUD_RESOURCEGROUP') | default('Default', true) }}"

ibmcos_instance_name: "{{ lookup('env', 'COS_INSTANCE_NAME') }}"
ibmcos_location_info: global
ibmcos_plan_type: standard
ibmcos_url: "https://s3.us.cloud-object-storage.appdomain.cloud"
ibmcos_username: "ibmcloud-iam-apikey"
