---
# Issuers need to be removed from old cert-manager namespace, as do the secrets and certificates associated with them.

# vars:
# - source_issuer_name
# - source_issuer_secret_name

# 1. Lookup Certificate
- name: "Delete Issuer : {{ source_issuer_name }} : Lookup original Certificate"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Certificate
    name: "{{ source_issuer_secret_name }}" # it seems the certificate will have the issuer secret's name instead of the issuer's name
    namespace: "{{ cert_manager_namespace }}"
  register: source_issuer_cert_info

# 2. Delete Certificate
- name: "Delete Issuer : {{ source_issuer_name }} : Delete original Certificate"
  when: source_issuer_cert_info['resources'] | length == 1
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Certificate
    name: "{{ source_issuer_secret_name }}" # it seems the certificate will have the issuer secret's name instead of the issuer's name
    namespace: "{{ cert_manager_namespace }}"

# 3. Lookup Issuer
- name: "Delete Issuer : {{ source_issuer_name }} : Lookup original Issuer"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Issuer
    name: "{{ source_issuer_name }}"
    namespace: "{{ cert_manager_namespace }}"
  register: source_issuer_info

# 4. Delete Issuer
- name: "Delete Issuer : {{ source_issuer_name }} : Delete original Issuer"
  when: source_issuer_info['resources'] | length == 1
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Issuer
    name: "{{ source_issuer_name }}"
    namespace: "{{ cert_manager_namespace }}"

# 5. Delete Secret - it's the last resource to be cleaned up
- name: "Delete Issuer : {{ source_issuer_name }} : Delete original Issuer's secret"
  include_tasks: tasks/delete_secret.yml
  vars:
    secret_name: "{{ source_issuer_secret_name }}"
