---
- name: "Delete Secret : {{ secret_name }} : {{ secret_name }} : Lookup original secret"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}"
    namespace: "{{ cert_manager_namespace }}"
  register: secret_info

- debug:
    msg: "Secret {{ secret_name }} does not exist, it might have already been deleted!"
  when: secret_info.resources | length == 0

- name: "Delete Secret : {{ secret_name }}: Delete original secret"
  when:
    - secret_info is defined
    - secret_info.resources is defined
    - secret_info.resources | length == 1
  vars:
    data: "{{ secret_info.resources[0] }}"
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}"
    namespace: "{{ cert_manager_namespace }}"
