---
# --- Prometheous settings --------------------------------------------------------------------------------------------
# Settings to update openshift monitoring to define a specific storage class for Prometheus logs
prometheus_retention_period: "{{ lookup('env', 'PROMETHEUS_RETENTION_PERIOD') | default('15d', true) }}"
prometheus_storage_class: "{{ lookup('env', 'PROMETHEUS_STORAGE_CLASS') }}"
prometheus_storage_size: "{{ lookup('env', 'PROMETHEUS_STORAGE_SIZE') | default('300Gi', true) }}"
prometheus_alertmgr_storage_class: "{{ lookup('env', 'PROMETHEUS_ALERTMGR_STORAGE_CLASS') }}"
prometheus_alertmgr_storage_size: "{{ lookup('env', 'PROMETHEUS_ALERTMGR_STORAGE_SIZE') | default('20Gi', true) }}"

# Settings to update openshift user workload monitoring to define a specific storage class and size for Prometheus logs
prometheus_userworkload_retention_period: "{{ lookup('env', 'PROMETHEUS_USERWORKLOAD_RETENTION_PERIOD') | default('15d', true) }}"
prometheus_userworkload_storage_class: "{{ lookup('env', 'PROMETHEUS_USERWORKLOAD_STORAGE_CLASS') | default(lookup('env', 'PROMETHEUS_STORAGE_CLASS'), true) }}"
prometheus_userworkload_storage_size: "{{ lookup('env', 'PROMETHEUS_USERWORKLOAD_STORAGE_SIZE') | default('300Gi', true) }}"

# Settings to set grafana to define a specific storage class and size
grafana_instance_storage_class: "{{ lookup('env', 'GRAFANA_INSTANCE_STORAGE_CLASS') }}"
grafana_instance_storage_size: "{{ lookup('env', 'GRAFANA_INSTANCE_STORAGE_SIZE') | default('10Gi', true) }}"

# Settings to set grafana location
grafana_namespace: "{{ lookup('env', 'GRAFANA_NAMESPACE') | default('grafana', true) }}"
