---
# Ansible can't support block retries, this is a relatively simple workaround
# to achieve the same thing
# https://github.com/ansible/ansible/issues/46203#issuecomment-556013701
- name: "Wait until all SBO resources to have 'spec.application' defined"
  block:
    - name: "wait : Set the retry count"
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count|int + 1 }}"
        sbo_count: 0
        ready_sbo_count: 0

    - name: "Lookup SBO resources"
      kubernetes.core.k8s_info:
        api_version: binding.operators.coreos.com/v1alpha1
        kind: ServiceBinding
        label_selectors:
          - mas.ibm.com/instanceId={{ mas_instance_id }}
      register: sbo_resources_info

    - name: "Check if SBO resources include 'spec.application' in its definition"
      set_fact:
        sbo_count: "{{ sbo_count|int + 1 }}"
        ready_sbo_count: "{{ ready_sbo_count|int + 1 if (item.spec.application is defined) else ready_sbo_count|int}}"
      with_items: "{{ sbo_resources_info.resources }}"
      loop_control:
        label: "Does SBO resource '{{ item.metadata.name }}' include 'spec.application' in its definition? {{ (item.spec.application is defined) if (item.spec.application is defined) else 'NO!!! THIS SB STILL NEEDS TO BE UPDATED!'  }}"
        # ready_worker_count: "{{ ready_worker_count|int + 1 if (item.kubeVersion == item.targetVersion) else ready_worker_count|int}}"

    - name: "Fail if one or more SBO resources are still pending to include 'spec.application' in its definition"
      assert:
        that: ready_sbo_count == sbo_count
        fail_msg: "[{{ retry_count }}/30] {{ ready_sbo_count}} of {{ sbo_count }} SBO resources already includes 'spec.application' in its definition"

  rescue:
    - name: "wait : Give up after 30 attempts (approx 30 minutes)"
      assert:
        that: retry_count|int < 30
        fail_msg: Timed out waiting for SBO resources to be updated with 'spec.application'

    - name: "wait : Wait for 60 seconds before checking again"
      pause:
        seconds: 60

    - include_tasks: wait_for_spec_application.yml
