---

- name: Debug no-op mode
  when: dns_provider == ""
  debug:
    msg: "dns_provider is not set, so this role will take no action"

# 1. Check required properties
# -----------------------------------------------------------------------------
- name: "Check required properties"
  when: dns_provider != ""
  assert:
    that:
      - dns_provider is in ['cis', 'cloudflare']
      - mas_instance_id is defined and mas_instance_id != ""


# 2. Run provider task
# -----------------------------------------------------------------------------
- name: "Run the provider specific task"
  when: dns_provider != ""
  include_tasks: tasks/providers/{{ dns_provider }}.yml


# 3. Set custom cp4d route based on the custom cluster issuer
# -----------------------------------------------------------------------------
- name: "Set up CP4D route under the appsuite domain"
  when:
    - dns_provider != ""
    - cpd_instance_namespace is defined and cpd_instance_namespace != ""
  include_tasks: tasks/cp4d.yml
