---

# 1. Getting cluster version details
# -----------------------------------------------------------------------------
- name: "Get ocp cluster version details "
  k8s_info:
    kind: ClusterVersion
    name: version
  register: cluster_details

- name: Print cluster id
  debug:
    msg: "clusterID : {{ cluster_details.resources[0].spec.clusterID }}"


# 2. Apply (with force) the ClusterVersion resource
# -----------------------------------------------------------------------------
- name: Set Cluster Version Definition
  vars:
    cluster_id: "{{ cluster_details.resources[0].spec.clusterID }}"
  kubernetes.core.k8s:
    apply: yes
    force: yes
    state: present
    definition: "{{ lookup('template', 'templates/cluster-version.yml') }}"
