# below are the resources needed to install foundation services with ibm-cert-manager in 'ibm-common-services' namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-common-services-operators
  namespace: ibm-common-services
spec:
  targetNamespaces:
  - ibm-common-services
