---
# 1. Upgrade to cert-manager v1.5 (IBM badged version)
# -----------------------------------------------------------------------------
# Note:
#   - This is not a requirement for MAS itself, but for CP4D v4
#   - MAS should not experience any outage during this upgrade, but certificates etc will
#     not be able to be updated during this process
#   - This is a cluster wide change, anything else in the using using cert-manager will
#     need to be updated to refer to the new namespace

- name: "Migrate cert-manager to ibm-common-services"
  include_tasks: tasks/cert_manager_upgrade/upgrade.yml
