---
# 1. Determine CP4D admin login credentials
# -----------------------------------------------------------------------------
- name: "Lookup the cp4d admin user secret"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "admin-user-details"
    namespace: "{{ cpd_instance_namespace }}"
  register: cpd_admin_creds

- name: "Check that we found the secret holding the admin credentials"
  assert:
    that:
      - cpd_admin_creds.resources is defined
      - cpd_admin_creds.resources | length == 1
      - cpd_admin_creds.resources[0].data.initial_admin_password is defined
      - cpd_admin_creds.resources[0].data.initial_admin_password != ""
    fail_msg: "Unable to find initial_admin_password in Secret/admin-user-details in {{ cpd_instance_namespace }}"

- name: "Query the existing cp4d instance Login Credential"
  set_fact:
    cpd_admin_username: "admin"
    cpd_admin_password: "{{ cpd_admin_creds.resources[0].data.initial_admin_password | b64decode }}"
