---
# 1. Debug
# -----------------------------------------------------------------------------
- name: "Check that CPD Service name and product version has been provided"
  assert:
    that:
      - cpd_service_name is defined and cpd_service_name != ""
      - cpd_product_version is defined and cpd_product_version != ""
    fail_msg: "CPD service name (cpd_service_name) and version (cpd_product_version) are required parameter to run this role"

- debug:
    msg:
      - "CPD operators namespace ................ {{ cpd_operators_namespace }}"
      - "CPD instance namespace ................. {{ cpd_instance_namespace }}"
      - "CPD service ............................ {{ cpd_service_name }}"
      - "CPD product version .................... {{ cpd_product_version }}"


# 2. Run the installation
# -----------------------------------------------------------------------------
- name: "Run install"
  include_tasks: "install.yml"
