---
# 1. Check for the Red Hat Catalog Source
# -----------------------------------------------------------------------------
# In IBMCloud ROKS we have seen delays of over an hour before the catalog is
# ready to use.
- name: Check if Red Hat Catalog is ready
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    name: redhat-operators
    namespace: openshift-marketplace
    kind: CatalogSource
  register: redhat_catalog_info
  retries: 90 # ~approx 1 1/2 hours before we give up
  delay: 60 # seconds
  until:
    - redhat_catalog_info.resources is defined
    - redhat_catalog_info.resources | length > 0
    - redhat_catalog_info.resources[0].status.connectionState.lastObservedState is defined
    - redhat_catalog_info.resources[0].status.connectionState.lastObservedState == "READY"


# 2. Check for router and ingress secrets
# -----------------------------------------------------------------------------
- name: "Lookup the default cluster ingress secret"
  include_tasks: "{{ role_path }}/../../common_tasks/get_ingress_cert.yml"
