---

# 1. Install SLS
# -----------------------------------------------------------------------------
# If the user has provided sls_url then it means they don't want to install
# SLS locally, but instead just generate a SLSCfg for the instance defined by
# the input variables
- include_tasks: tasks/install/main.yml
  when:
    - sls_url is not defined or sls_url == ""


# 2. Generate the SLS configuration for MAS
# -----------------------------------------------------------------------------
- include_tasks: tasks/gencfg/main.yml
  when:
    - mas_instance_id is defined and mas_instance_id != ""
    - mas_config_dir is defined and mas_config_dir != ""
