---

# 1. Configure COS using IBM Cloud Object Storage (ibmcos) or OpenShift Container Storage (ocs)
# ---------------------------------------------------------------------------------------------------------------------
- name: "Run the task for the appropriate provider"
  include_tasks: tasks/providers/{{ cos_type }}.yml
